/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikumpbo9;

import javax.swing.JPanel;

/**
 *
 * @author Acer
 */
public class MainJFrame extends javax.swing.JFrame {

    private JPanel mainPanel;

    public MainJFrame() {
        initComponents();
        setupMainPanel();
    }

    private void setupMainPanel() {
        mainPanel = new JPanel();
        getContentPane().add(mainPanel);
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());

    public void changeMainPanel(javax.swing.JPanel panel) {
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    public class Main {

        public static void main(String args[]) {
            MainJFrame frame = new MainJFrame();
            frame.changeMainPanel(new TambahDataPanel());
            frame.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        tambahDataButton = new javax.swing.JButton();
        lihatDataButton = new javax.swing.JButton();
        basePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setBackground(new java.awt.Color(0, 255, 255));

        tambahDataButton.setText("Tambah Data");
        tambahDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataButtonActionPerformed(evt);
            }
        });

        lihatDataButton.setText("Lihat Data");
        lihatDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambahDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lihatDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(tambahDataButton)
                .addGap(18, 18, 18)
                .addComponent(lihatDataButton)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        basePanel.setBackground(new java.awt.Color(255, 255, 255));
        basePanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(basePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataButtonActionPerformed
        changeMainPanel(new TambahDataPanel());
    }//GEN-LAST:event_tambahDataButtonActionPerformed

    private void lihatDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDataButtonActionPerformed
        changeMainPanel(new LihatDataPanel());
    }//GEN-LAST:event_lihatDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton lihatDataButton;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton tambahDataButton;
    // End of variables declaration//GEN-END:variables
}
