/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package praktikumpbo9;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */

public class TambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form TambahDataPanel
     */
    public TambahDataPanel() {
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        prodiComboBox = new javax.swing.JComboBox<>();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        aktifCheckBox = new javax.swing.JCheckBox();
        kirimButton = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setText("Tambah Data Mahasiswa");
        jTextField1.setBorder(null);

        jTextField2.setText("Nama");
        jTextField2.setBorder(null);

        jTextField3.setText("NIM");
        jTextField3.setBorder(null);

        jTextField4.setText("Prodi");
        jTextField4.setBorder(null);

        jTextField5.setText("Jenis Kelamin");
        jTextField5.setBorder(null);

        jTextField7.setText("Status");
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro", " ", " " }));
        prodiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiComboBoxActionPerformed(evt);
            }
        });

        lakiLakiRadioButton.setText("Laki Laki");

        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        aktifCheckBox.setText("Aktif");

        kirimButton.setBackground(new java.awt.Color(0, 255, 255));
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lakiLakiRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(perempuanRadioButton)
                                .addGap(27, 27, 27))
                            .addComponent(namaTextField)
                            .addComponent(nimTextField)
                            .addComponent(prodiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kirimButton)
                                    .addComponent(aktifCheckBox))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aktifCheckBox))
                .addGap(18, 18, 18)
                .addComponent(kirimButton)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
   
    // Ambil data dari form
    String nama = namaTextField.getText();
    String nim = nimTextField.getText();
    String prodi = (String) prodiComboBox.getSelectedItem();
    String jenisKelamin = "";
    
    if (lakiLakiRadioButton.isSelected()) {
        jenisKelamin = "Laki-Laki";
    } else if (perempuanRadioButton.isSelected()) {
        jenisKelamin = "Perempuan";
    }
    
    boolean isActive = aktifCheckBox.isSelected();

    // ========== VALIDASI DASAR ==========
    
    // Validasi NIM tidak boleh kosong
    if (nim.equals("")) {
        JOptionPane.showMessageDialog(this, "Data gagal diproses:\n- NIM tidak terisi");
        return;
    }
    
    // Validasi format NIM
    if (nim.matches(".*[a-zA-Z].*") || nim.matches(".*[^a-zA-Z0-9].*")) {
        JOptionPane.showMessageDialog(this, "Data gagal diproses:\n- NIM harus angka saja");
        return;
    }
    
    // Validasi panjang NIM
    if (nim.length() != 10) {
        JOptionPane.showMessageDialog(this, "Data gagal diproses:\n- NIM harus 10 digit");
        return;
    }

    // ========== CEK APAKAH NIM SUDAH ADA ==========
    boolean nimSudahAda = false;
    Mahasiswa mahasiswaDitemukan = null;
    
    for (Mahasiswa mhs : Mahasiswa.mahasiswas) {
        if (mhs.getNim().equals(nim)) {
            nimSudahAda = true;
            mahasiswaDitemukan = mhs;
            break;
        }
    }

    // ========== JIKA NIM SUDAH ADA → TAWARKAN UPDATE/DELETE ==========
    if (nimSudahAda) {
        Object[] options = {"Update", "Delete", "Batal"};
        int pilihan = JOptionPane.showOptionDialog(this,
                "NIM " + nim + " sudah terdaftar atas nama " + mahasiswaDitemukan.getNama() + "\n\nApa yang ingin Anda lakukan?",
                "Data Sudah Ada",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[2]);

        // ========== PILIH UPDATE ==========
        if (pilihan == 0) { // Update
            // Validasi untuk Update
            if (nama.equals("")) {
                JOptionPane.showMessageDialog(this, "Update gagal:\n- Nama tidak terisi");
                return;
            }
            if (jenisKelamin.equals("")) {
                JOptionPane.showMessageDialog(this, "Update gagal:\n- Jenis kelamin belum dipilih");
                return;
            }
            if (prodi == null || prodi.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Update gagal:\n- Prodi belum dipilih");
                return;
            }
            if (!nama.matches("^[a-zA-Z ]+$")) {
                JOptionPane.showMessageDialog(this, "Update gagal:\n- Nama hanya boleh huruf dan spasi");
                return;
            }

            // Konfirmasi Update
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Update data mahasiswa:\n\n"
                    + "NIM: " + nim + "\n"
                    + "Nama Lama: " + mahasiswaDitemukan.getNama() + "\n"
                    + "Nama Baru: " + nama + "\n\n"
                    + "Lanjutkan?",
                    "Konfirmasi Update",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                mahasiswaDitemukan.setNama(nama);
                mahasiswaDitemukan.setJenisKelamin(jenisKelamin);
                mahasiswaDitemukan.setProdi(prodi);
                mahasiswaDitemukan.setActive(isActive);
                JOptionPane.showMessageDialog(this, "✓ Sukses mengupdate data mahasiswa " + nama);
                clearForm();
            }
        }
        
        // ========== PILIH DELETE ==========
        else if (pilihan == 1) { // Delete
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Hapus data mahasiswa:\n\n"
                    + "NIM: " + nim + "\n"
                    + "Nama: " + mahasiswaDitemukan.getNama() + "\n"
                    + "Prodi: " + mahasiswaDitemukan.getProdi() + "\n\n"
                    + "Data akan dihapus permanen!",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirm == JOptionPane.YES_OPTION) {
                Mahasiswa.mahasiswas.remove(mahasiswaDitemukan);
                JOptionPane.showMessageDialog(this, "✓ Sukses menghapus data mahasiswa");
                clearForm();
            }
        }
        
        return; // Hentikan eksekusi
    }

    // ========== JIKA NIM BELUM ADA → TAMBAH DATA BARU ==========
    
    // Validasi lengkap untuk Tambah
    if (nama.equals("")) {
        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n- Nama belum terisi");
        return;
    }
    if (jenisKelamin.equals("")) {
        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n- Jenis kelamin belum dipilih");
        return;
    }
    if (prodi == null || prodi.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n- Prodi belum dipilih");
        return;
    }
    if (!nama.matches("^[a-zA-Z ]+$")) {
        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan:\n- Nama hanya boleh huruf dan spasi");
        return;
    }

    // Tambahkan data baru
    Mahasiswa mahasiswaBaru = new Mahasiswa(nama, nim, jenisKelamin, prodi, isActive);
    Mahasiswa.mahasiswas.add(mahasiswaBaru);
    JOptionPane.showMessageDialog(this, "Sukses menambahkan data mahasiswa " + nama);
    clearForm();

    
    }//GEN-LAST:event_kirimButtonActionPerformed
    
    private void prodiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton kirimButton;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> prodiComboBox;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
    namaTextField.setText("");
    nimTextField.setText("");
    lakiLakiRadioButton.setSelected(false); // Atau set salah satunya menjadi true jika harus memilih
    perempuanRadioButton.setSelected(false); // Atau gunakan ButtonGroup untuk memastikan hanya satu yang terpilih
    aktifCheckBox.setSelected(false);
}
}
